server:
  port: 8080

spring:
  application:
    name: GATEWAY-API
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: Marque-service-route
          uri: lb://MARQUESERVICE
          predicates:
            - Path=/marques/**
        - id: Article-service-route
          uri: lb://ARTICLESERVICE
          predicates:
            - Path=/articles/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
